mysql:
  name: QA
  host: "127.0.0.1"
  port: 3306
  user: root
  pass:

session:
  name: QA-session
  driver: redis

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  user: root
  pass:

aes:
  key: 

mongodb:
  host: "127.0.0.1"
  port: 27017
  user: 
  pass:
  db: QA

url:
  host: "https://"