//不知道为什么，这里一定得有个config.yaml文件，否则会报错

mysql:
  name: QA
  host: "127.0.0.1"
  port: 3306
  user: root
  pass:

session:
  name: QA-session
  driver: redis

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  user: root
  pass:

aes:
  key: 

mongodb:
  host: "127.0.0.1"
  port: 27017
  user: 
  pass:
  db: QA
  collection: QA

url:
  host: "https://example.com"

key: 
